"""empty message

Revision ID: 5f9407105453
Revises: d85eb4650aee
Create Date: 2024-02-01 06:50:16.967463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9407105453'
down_revision = 'd85eb4650aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fees')
    # ### end Alembic commands ###
