"""empty message

Revision ID: 6b47edcee235
Revises: 8396da4f1fcc
Create Date: 2024-02-08 13:27:20.466154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b47edcee235'
down_revision = '8396da4f1fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade', ['grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_id')

    # ### end Alembic commands ###
