"""empty message

Revision ID: 717faf1d663f
Revises: ef3be11e5c24
Create Date: 2024-02-05 11:20:55.969677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717faf1d663f'
down_revision = 'ef3be11e5c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_teachers_second_name'), ['second_name'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index('ix_students_first_name')
        batch_op.create_index(batch_op.f('ix_students_first_name'), ['first_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_first_name'))
        batch_op.create_index('ix_students_first_name', ['first_name'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_second_name'))
        batch_op.drop_index(batch_op.f('ix_teachers_first_name'))

    op.drop_table('teachers')
    # ### end Alembic commands ###
