"""empty message

Revision ID: a0c1107021ad
Revises: 0fc2fd7e218b
Create Date: 2024-02-02 13:15:04.929504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c1107021ad'
down_revision = '0fc2fd7e218b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('fee_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('fee_paid',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    # ### end Alembic commands ###
