"""empty message

Revision ID: aa2d8beb9b9e
Revises: 2b5f8088b5c1
Create Date: 2024-02-01 09:16:22.934740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2d8beb9b9e'
down_revision = '2b5f8088b5c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_constraint('fees_student_id_fkey', type_='foreignkey')
        batch_op.drop_column('student_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'fees', ['fee_total'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fee_total')

    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fees_student_id_fkey', 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###
