"""empty message

Revision ID: aeffdc7f42e9
Revises: d0da92ea841b
Create Date: 2024-02-02 13:11:56.714135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeffdc7f42e9'
down_revision = 'd0da92ea841b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee_paid', sa.Numeric(precision=10, scale=2), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee_paid', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))

    # ### end Alembic commands ###
