"""empty message

Revision ID: b226b1994c77
Revises: 36dd778a84df
Create Date: 2024-02-02 13:03:35.420012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b226b1994c77'
down_revision = '36dd778a84df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fee_paid', sa.String(length=255), nullable=False, server_default=0))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'fee_paid')

    # ### end Alembic commands ###
