"""empty message

Revision ID: cbaaedcec5eb
Revises: 04f4fa8ddfcb
Create Date: 2024-02-09 11:58:48.386148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbaaedcec5eb'
down_revision = '04f4fa8ddfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade', ['grade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_id')

    # ### end Alembic commands ###
