"""empty message

Revision ID: eab3540e9d91
Revises: 7d8a1870f12b
Create Date: 2024-02-02 10:57:38.683732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab3540e9d91'
down_revision = '7d8a1870f12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('students_fee_total_fkey', type_='foreignkey')
        batch_op.drop_column('fee_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_total', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('students_fee_total_fkey', 'fees', ['fee_total'], ['id'])

    # ### end Alembic commands ###
