"""empty message

Revision ID: f03c232c9563
Revises: aa2d8beb9b9e
Create Date: 2024-02-02 10:51:45.828903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f03c232c9563'
down_revision = 'aa2d8beb9b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('fee_total',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.drop_constraint('students_fee_total_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key('students_fee_total_fkey', 'fees', ['fee_total'], ['id'])
        batch_op.alter_column('fee_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
