name: Deploy Flask App and Auto Merge PR

on:
  pull_request_target:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
      - unlabeled
      - labeled
      - unlocked

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      # Step 2: Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: make test
        env:
          THIS_SECRET: ${{ secrets.THIS_SECRET }}

  auto-merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Merge PR if conditions are met
      - name: Merge PR if conditions are met
        if: github.event.pull_request.user.login == 'stancoder-005'  # Check if the PR was created by the correct user
        run: |
          curl -X PUT -H "Authorization: Bearer ${{ secrets.THIS_SECRET }}" \
            -d '{"commit_message": "Automated PR merge", "merge_method": "merge"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/merge
